# Generated by Django 4.2.18 on 2025-02-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('key_skills', models.TextField()),
                ('job_title', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('education', models.TextField()),
                ('companies', models.TextField()),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('resume_content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
